// List of major institutions in Nigeria for standard dropdown selections
export interface University {
  code: string;
  name: string;
}

export const NIGERIAN_UNIVERSITIES: University[] = [
  { code: "ABU", name: "Ahmadu Bello University, Zaria (ABU)" },
  { code: "AAU", name: "Ambrose Alli University, Ekpoma (AAU)" },
  { code: "ABSU", name: "Abia State University, Uturu (ABSU)" },
  { code: "ABUAD", name: "Afe Babalola University, Ado-Ekiti (ABUAD)" },
  { code: "AKSU", name: "Akwa Ibom State University, Ogbere (AKSU)" },
  { code: "ANSU", name: "Chukwuemeka Odumegwu Ojukwu University, Uli (COOU)" },
  { code: "AUCHIPOLY", name: "Auchi Polytechnic, Auchi" },
  { code: "BABCOCK", name: "Babcock University, Ilishan-Remo" },
  { code: "BAYERO", name: "Bayero University, Kano (BUK)" },
  { code: "BSU", name: "Benue State University, Makurdi (BSU)" },
  { code: "DELSU", name: "Delta State University, Abraka (DELSU)" },
  { code: "DOU", name: "Dennis Osadebay University, Asaba (DOU)" },
  { code: "DSUST", name: "Delta State University of Science and Technology, Ozoro (DSUST)" },
  { code: "EBSU", name: "Ebonyi State University, Abakaliki (EBSU)" },
  { code: "EKSU", name: "Ekiti State University, Ado-Ekiti (EKSU)" },
  { code: "ESUT", name: "Enugu State University of Science and Technology, Enugu (ESUT)" },
  { code: "FEDPOLY_ADO", name: "Federal Polytechnic, Ado-Ekiti" },
  { code: "FEDPOLY_NEK", name: "Federal Polytechnic, Nekede" },
  { code: "FEDPOLY_OFF", name: "Federal Polytechnic, Offa" },
  { code: "FEDPOLY_OKO", name: "Federal Polytechnic, Oko" },
  { code: "FEPO", name: "Federal Polytechnic, Orogun" },
  { code: "FUNAAB", name: "Federal University of Agriculture, Abeokuta (FUNAAB)" },
  { code: "FUPRE", name: "Federal University of Petroleum Resources, Effurun (FUPRE)" },
  { code: "FUTA", name: "Federal University of Technology, Akure (FUTA)" },
  { code: "FUTO", name: "Federal University of Technology, Owerri (FUTO)" },
  { code: "FUTMINNA", name: "Federal University of Technology, Minna (FUTMINNA)" },
  { code: "GSU", name: "Gombe State University, Gombe (GSU)" },
  { code: "IMSU", name: "Imo State University, Owerri (IMSU)" },
  { code: "KASU", name: "Kaduna State University, Kaduna (KASU)" },
  { code: "KSU", name: "Kogi State University, Anyigba (KSU)" },
  { code: "KUST", name: "Kano University of Science and Technology, Wudil" },
  { code: "KWASU", name: "Kwara State University, Malete (KWASU)" },
  { code: "LASU", name: "Lagos State University, Ojo (LASU)" },
  { code: "LAUTECH", name: "Ladoke Akintola University of Technology, Ogbomoso (LAUTECH)" },
  { code: "MOUAU", name: "Michael Okpara University of Agriculture, Umudike (MOUAU)" },
  { code: "NASARAWA", name: "Nasarawa State University, Keffi" },
  { code: "NOURA", name: "Nile University of Nigeria, Abuja" },
  { code: "NOVENA", name: "Novena University, Ogume-Amai" },
  { code: "OAU", name: "Obafemi Awolowo University, Ile-Ife (OAU)" },
  { code: "OOU", name: "Olabisi Onabanjo University, Ago-Iwoye (OOU)" },
  { code: "PLASU", name: "Plateau State University, Bokkos (PLASU)" },
  { code: "PTI", name: "Petroleum Training Institute, Effurun (PTI)" },
  { code: "RSUST", name: "Rivers State University, Port Harcourt (RSU)" },
  { code: "TASUED", name: "Tai Solarin University of Education, Ijebu Ode (TASUED)" },
  { code: "UI", name: "University of Ibadan (UI)" },
  { code: "UNIBEN", name: "University of Benin (UNIBEN)" },
  { code: "UNICAL", name: "University of Calabar (UNICAL)" },
  { code: "UNIDEL", name: "University of Delta, Agbor (UNIDEL)" },
  { code: "UNIUYO", name: "University of Uyo (UNIUYO)" },
  { code: "UNILAG", name: "University of Lagos (UNILAG)" },
  { code: "UNILORIN", name: "University of Ilorin (UNILORIN)" },
  { code: "UNIMAID", name: "University of Maiduguri (UNIMAID)" },
  { code: "UNIPORT", name: "University of Port Harcourt (UNIPORT)" },
  { code: "UNIZIK", name: "Nnamdi Azikiwe University, Awka (UNIZIK)" },
  { code: "UNN", name: "University of Nigeria, Nsukka (UNN)" },
  { code: "USTA", name: "Federal University, Dutse" },
  { code: "WDU", name: "Western Delta University, Oghara (WDU)" },
  { code: "YABATECH", name: "Yaba College of Technology, Yaba" }
];
